version: 2.1

orbs:

  helm-aws-package:
    orbs:
      build-tools: circleci/build-tools@2.9.1
      aws-cli: circleci/aws-cli@2.0.3

    executors:
      base:
        parameters:
          image-tag:
            description: >-
              The `cimg/base` image tag to use. Defaults to `stable`.
            type: string
            default: stable
        docker:
          - image: cimg/base:<< parameters.image-tag >>

    commands:
      init:
        description: Initialize the environment
        steps:
          - run:
              name: Install Helm
              command: |
                    curl -fsSL -o get-helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 && \
                    chmod +x get-helm.sh && \
                    ./get-helm.sh && \
                    rm ./get-helm.sh          

    jobs:

      publish:
        description: Packages and publishes a Helm chart to AWS S3
        parameters:

          executor-image-tag:
            description: >-
              Image tag for the executor.
            type: string
            default: stable

          chart-path:
            description: >-
              Relative path to the Helm chart directory
            type: string
            default: .

          s3_bucket_name:
            description: >-
              Env var containing the name of the S3 bucket used for chart storage
              Defaults to `CHARTMUSEUM_S3_BUCKET_NAME`.
            type: env_var_name
            default: CHARTMUSEUM_S3_BUCKET_NAME

          s3_object_key_prefix:
            description: >-
              String prefixed to object names uploaded to the S3 bucket
            type: string
            default: charts

        executor:
          name: base
          image-tag: << parameters.executor-image-tag >>

        steps:
          - init
          - aws-cli/install
          - checkout

          - run:
              name: Package
              command: |
                helm dependency update << parameters.chart-path >>
                helm package << parameters.chart-path >>

          - build-tools/ensure-command:
              command: aws

          # - run:
          #     name: Upload
          #     command: |
          #       for file in *.tgz; do
          #         aws s3 cp "$file" "s3://<< parameters.s3_bucket_name >>/<< parameters.s3_object_key_prefix >>/$file"
          #       done

workflows:
  version: 2

  publish-chart:
    jobs:
      - helm-aws-package/publish:
          chart-path: ./chart
